### PR TITLE
Include tutorial images

### PR DESCRIPTION
**Pull request by AlexandraImbrisca**

### CODE REVIEW

**Review by tatiana-s — APPROVED** [review]
Looks good, the only nit is that (assuming the deployed version already uses this PR), under 'Access the chat' you can see a 'screenshot taken' notification in one of the screenshots.

**Comment by AlexandraImbrisca** [comment]
The deployed project uses an old version of the screenshots. I updated the screenshots afterwards (and include a cursor as well).

**Review by nataliakrylova — APPROVED** [review]
Looks great!

(nit) I think removing everything around tab content (bar on the bottom and the browser UI on the top)  would make it look a bit nicer :)

**Comment by AlexandraImbrisca** [comment]
Good idea! I modified the images and added a small black border because both the page and the images have the same white background that can be hardly distinguished without a border.

**Pull request merged**
